package git.zenyfh.vanilla_adjustments;

import net.neoforged.neoforge.common.ModConfigSpec;

public final class VanillaAdjustConfig {
    public static final ModConfigSpec SERVER_SPEC;

    public static final ModConfigSpec.BooleanValue ENDER_PEARL_RADIUS_LIMIT_ENABLED;
    public static final ModConfigSpec.IntValue ENDER_PEARL_MAX_RADIUS;
    public static final ModConfigSpec.BooleanValue ENDER_PEARL_LIMIT_USES_HORIZONTAL_DISTANCE;
    public static final ModConfigSpec.EnumValue<EnderPearlLimitBehaviour> ENDER_PEARL_LIMIT_BEHAVIOUR;
    public static final ModConfigSpec.BooleanValue ENDER_PEARL_LIMIT_SEND_MESSAGE;
    public static final ModConfigSpec.BooleanValue DEEPSLATE_FLUID_GENERATORS;
    public static final ModConfigSpec.BooleanValue REPLACE_COBBLESTONE_GENERATORS_WITH_COBBLED_DEEPSLATE;
    public static final ModConfigSpec.BooleanValue REPLACE_STONE_GENERATORS_WITH_DEEPSLATE;
    public static final ModConfigSpec.BooleanValue REPLACE_BASALT_GENERATORS_WITH_DEEPSLATE;
    public static final ModConfigSpec.BooleanValue REPLACE_CREATE_DECORATIVE_STONE_GENERATORS_WITH_DEEPSLATE;
    public static final ModConfigSpec.BooleanValue PLAYER_PLACED_WATER_SOURCE_LIMIT_ENABLED;
    public static final ModConfigSpec.BooleanValue TRACK_DISPENSER_PLACED_WATER_AS_ARTIFICIAL;
    public static final ModConfigSpec.BooleanValue DEBUG_PLAYER_PLACED_WATER_SOURCES;
    public static final ModConfigSpec.BooleanValue DISABLE_DRIPSTONE_LAVA_GENERATION;
    public static final ModConfigSpec.BooleanValue DISABLE_DRIPSTONE_WATER_GENERATION;
    public static final ModConfigSpec.BooleanValue DEBUG_DRIPSTONE_CAULDRON_BLOCKING;
    public static final ModConfigSpec.BooleanValue DISABLE_ELYTRA_ROCKET_BOOST;
    public static final ModConfigSpec.BooleanValue DISABLE_ELYTRA_ROCKET_BOOST_SEND_MESSAGE;
    public static final ModConfigSpec.BooleanValue DEATH_TIMER_DISPLAY_ENABLED;
    public static final ModConfigSpec.IntValue DEATH_TIMER_TEXT_COLOR;
    public static final ModConfigSpec.BooleanValue BENEFICIAL_EFFECT_HUNGER_DRAIN_ENABLED;
    public static final ModConfigSpec.DoubleValue BENEFICIAL_EFFECT_HUNGER_EXHAUSTION_PER_SECOND_PER_STRENGTH;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();
        builder.push("enderPearlRadiusLimit");
        ENDER_PEARL_RADIUS_LIMIT_ENABLED = builder
                .comment("When true, player-thrown ender pearls cannot teleport farther than enderPearlMaxRadius from their throw position.")
                .define("enderPearlRadiusLimitEnabled", true);
        ENDER_PEARL_MAX_RADIUS = builder
                .comment("Maximum allowed ender pearl travel distance in blocks. Horizontal X/Z distance is used by default.")
                .defineInRange("enderPearlMaxRadius", 256, 1, 30_000);
        ENDER_PEARL_LIMIT_USES_HORIZONTAL_DISTANCE = builder
                .comment("When true, only X/Z distance counts toward the pearl radius limit. When false, full 3D distance is used.")
                .define("enderPearlLimitUsesHorizontalDistance", true);
        ENDER_PEARL_LIMIT_BEHAVIOUR = builder
                .comment("What to do when an ender pearl exceeds the configured radius. CANCEL blocks the teleport safely.")
                .defineEnum("enderPearlLimitBehaviour", EnderPearlLimitBehaviour.CANCEL);
        ENDER_PEARL_LIMIT_SEND_MESSAGE = builder
                .comment("When true, send the player a short actionbar message when an ender pearl teleport is blocked by the radius limit.")
                .define("enderPearlLimitSendMessage", true);
        builder.pop();

        builder.push("deepslateFluidGenerators");
        DEEPSLATE_FLUID_GENERATORS = builder
                .comment("When true, renewable stone-like blocks generated by fluid interactions are replaced with deepslate-themed blocks.")
                .define("deepslateFluidGenerators", true);
        REPLACE_COBBLESTONE_GENERATORS_WITH_COBBLED_DEEPSLATE = builder
                .comment("When true, fluid-generated cobblestone becomes cobbled deepslate.")
                .define("replaceCobblestoneGeneratorsWithCobbledDeepslate", true);
        REPLACE_STONE_GENERATORS_WITH_DEEPSLATE = builder
                .comment("When true, fluid-generated stone becomes deepslate.")
                .define("replaceStoneGeneratorsWithDeepslate", true);
        REPLACE_BASALT_GENERATORS_WITH_DEEPSLATE = builder
                .comment("When true, fluid-generated basalt becomes deepslate.")
                .define("replaceBasaltGeneratorsWithDeepslate", true);
        REPLACE_CREATE_DECORATIVE_STONE_GENERATORS_WITH_DEEPSLATE = builder
                .comment("When true, optional Create-style fluid generator outputs for renewable decorative stone blocks become deepslate without requiring Create as a dependency.")
                .define("replaceCreateDecorativeStoneGeneratorsWithDeepslate", true);
        builder.pop();

        builder.push("playerPlacedWaterSources");
        PLAYER_PLACED_WATER_SOURCE_LIMIT_ENABLED = builder
                .comment("When true, non-natural water and ice cannot create or contribute to infinite water sources. Natural water and natural ice remain infinite.")
                .define("playerPlacedWaterSourceLimitEnabled", true);
        TRACK_DISPENSER_PLACED_WATER_AS_ARTIFICIAL = builder
                .comment("When true, water placed by dispensers is also treated as non-natural for infinite-source prevention. Currently reserved for future dispenser tracking.")
                .define("trackDispenserPlacedWaterAsArtificial", false);
        DEBUG_PLAYER_PLACED_WATER_SOURCES = builder
                .comment("When true, logs non-natural water/ice tracking, freeze/thaw propagation, and blocked water source conversions.")
                .define("debugPlayerPlacedWaterSources", false);
        builder.pop();

        builder.push("elytraRockets");
        DISABLE_ELYTRA_ROCKET_BOOST = builder
                .comment("When true, firework rockets cannot be used to boost while elytra-flying.")
                .define("disableElytraRocketBoost", true);
        DISABLE_ELYTRA_ROCKET_BOOST_SEND_MESSAGE = builder
                .comment("When true, sends an actionbar message when an elytra rocket boost is blocked.")
                .define("disableElytraRocketBoostSendMessage", true);
        builder.pop();

        builder.push("dripstoneLava");
        DISABLE_DRIPSTONE_LAVA_GENERATION = builder
                .comment("When true, pointed dripstone cannot generate renewable lava by filling cauldrons.")
                .define("disableDripstoneLavaGeneration", true);
        DISABLE_DRIPSTONE_WATER_GENERATION = builder
                .comment("When true, pointed dripstone also cannot fill cauldrons with water. Default false.")
                .define("disableDripstoneWaterGeneration", false);
        DEBUG_DRIPSTONE_CAULDRON_BLOCKING = builder
                .comment("When true, logs blocked dripstone cauldron fluid generation.")
                .define("debugDripstoneCauldronBlocking", false);
        builder.pop();

        builder.push("deathTimerDisplay");
        DEATH_TIMER_DISPLAY_ENABLED = builder
                .comment("When true, show a client-side respawn countdown on the death screen while dead.")
                .define("deathTimerDisplayEnabled", true);
        DEATH_TIMER_TEXT_COLOR = builder
                .comment("RGB text colour for the death screen respawn countdown.")
                .defineInRange("deathTimerTextColor", 0xFFFFFF, 0x000000, 0xFFFFFF);
        builder.pop();

        builder.push("beneficialEffectHunger");
        BENEFICIAL_EFFECT_HUNGER_DRAIN_ENABLED = builder
                .comment("When true, active beneficial potion/status effects make player hunger drain faster. Harmful effects are ignored.")
                .define("beneficialEffectHungerDrainEnabled", true);
        BENEFICIAL_EFFECT_HUNGER_EXHAUSTION_PER_SECOND_PER_STRENGTH = builder
                .comment("Extra exhaustion added each second for each point of beneficial effect strength. Effect strength is the sum of amplifier + 1 across all active beneficial effects.")
                .defineInRange("beneficialEffectHungerExhaustionPerSecondPerStrength", 0.05D, 0.0D, 4.0D);
        builder.pop();
        SERVER_SPEC = builder.build();
    }

    private VanillaAdjustConfig() {
    }

    public enum EnderPearlLimitBehaviour {
        CANCEL
    }
}
