# Previous local instance path:
# instance_dir: "/media/zenyfh/GoodHDD/Games/Minecraft/Instances/UK Create (1)"
# mod_dir: "/media/zenyfh/GoodHDD/Games/Minecraft/Instances/UK Create (1)/mods"

instance_dir: "/home/zenyfh/Documents/curseforge/minecraft/Instances/UK Create (1)"
mod_dir: "/home/zenyfh/Documents/curseforge/minecraft/Instances/UK Create (1)/mods"
